version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nba_pg
    environment:
      POSTGRES_DB: injuries
      POSTGRES_USER: injuries
      POSTGRES_PASSWORD: injuries
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "injuries"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  dash:
    build:
      context: .
      dockerfile: dash_app/Dockerfile
    container_name: nba_dash
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    environment:
      DB_DSN: postgresql://injuries:injuries@postgres:5432/injuries

  etl-init:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: nba_etl_init
    depends_on:
      - postgres
    environment:
      DB_DSN: postgresql://injuries:injuries@postgres:5432/injuries
    command: ["python", "etl_teams_games.py"]

  etl-injuries:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: nba_etl_injuries
    depends_on:
      - postgres
    env_file: .env
    command: ["python", "etl_injuries.py"]

volumes:
  pgdata:
