version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nba_pg
    environment:
      POSTGRES_DB: ttfl_database
      POSTGRES_USER: ttfl
      POSTGRES_PASSWORD: ttfl
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ttfl"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  dash:
    build:
      context: .
      dockerfile: dash_app/Dockerfile
    container_name: nba_dash
    ports:
      - "8050:8050"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: postgresql://ttfl:ttfl@postgres:5432/ttfl_database

  etl-init:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: nba_etl_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: postgresql://ttfl:ttfl@postgres:5432/ttfl_database
    command: ["bash", "-lc", "python etl/etl_teams_games.py && python etl/etl_players.py"]

  etl-injuries:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: nba_etl_injuries
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    command: ["python", "etl/etl_injuries.py"]

volumes:
  pgdata:
