[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | build
  | dist
  | \.venv
  | \.env
)/
'''

[tool.pytest.ini_options]
pythonpath = [
    "."
]
